local Value = require(script.Graph.Value)
local Computed = require(script.Graph.Computed)
local Observer = require(script.Graph.Observer)
local peek = require(script.Graph.peek)
local New = require(script.Instances.New)
local Children = require(script.Instances.Children)
local Hydrate = require(script.Instances.Hydrate)
local Cleanup = require(script.Instances.Cleanup)
local OnChange = require(script.Instances.OnChange)
local OnEvent = require(script.Instances.OnEvent)
local Persistent = require(script.Graph.Persistent)
local Attribute = require(script.Instances.Attribute)
local AttributeChange = require(script.Instances.AttributeChange)
local AttributeOut = require(script.Instances.AttributeOut)
local Out = require(script.Instances.Out)
local cleanup = require(script.Util.cleanup)
local defaultEq = require(script.Util.defaultEq)
local phyEq = require(script.Util.phyEq)
local shallowEq = require(script.Util.shallowEq)
local doNothing = require(script.Util.doNothing)
local Table = require(script.Graph.Table)
local Tween = require(script.Animation.Tween)

return {
    Value = Value,
    Computed = Computed,
    Observer = Observer,
    peek = peek,
    New = New,
    Children = Children,
    Hydrate = Hydrate,
    Cleanup = Cleanup,
    OnChange = OnChange,
    OnEvent = OnEvent,
    Attribute = Attribute,
    AttributeChange = AttributeChange,
    AttributeOut = AttributeOut,
    Out = Out,
    Persistent = Persistent,
    cleanup = cleanup,
    defaultEq = defaultEq,
    phyEq = phyEq,
    shallowEq = shallowEq,
    doNothing = doNothing,
    Table = Table,
    Tween = Tween
}